name: "Static Analysis"
on: ["push", "pull_request"]
jobs:
  Static-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Static Code Analysis
        uses: dominikh/staticcheck-action@v1

  Go-Sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.9.5
        with:
          # Temporary ignoring G301,G302,G306
          args: -exclude=G204,G301,G302,G304,G306 -exclude-dir=\.*test\.* ./...